apiVersion: apps/v1
kind: Deployment
metadata:
  name: bng
spec:
  template:
    spec:
      containers:
        - name: bng
          args:
            - demo
            - --subscribers=100
            - --duration=24h
            - --api-port=8080
            - --nexus-url=http://wifi-nexus.demo-wifi.svc:9000
            - --lease-mode=ttl-sticky
            - --lease-ttl=300s
          envFrom:
            - configMapRef:
                name: wifi-wifi-config
