# BNG StatefulSet for distributed demo
# Uses StatefulSet for stable network identity when connecting to Nexus cluster
apiVersion: v1
kind: Service
metadata:
  name: bng
  labels:
    app: bng
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
  clusterIP: None  # Headless for StatefulSet
  selector:
    app: bng
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bng
  labels:
    app: bng
spec:
  serviceName: bng
  replicas: 2
  selector:
    matchLabels:
      app: bng
  template:
    metadata:
      labels:
        app: bng
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: bng
          image: ghcr.io/codelaboratoryltd/bng:latest
          args:
            - demo
            - --subscribers=50
            - --duration=24h
            - --api-port=8080
            - --nexus-url=http://distributed-nexus.demo-distributed.svc:9000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BNG_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
