# Standby BNG instance
# Monitors active peer and takes over on failure
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bng-standby
  labels:
    app: bng
    role: standby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bng
      role: standby
  template:
    metadata:
      labels:
        app: bng
        role: standby
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: bng
          image: ghcr.io/codelaboratoryltd/bng:latest
          args:
            - demo
            - --subscribers=0
            - --duration=24h
            - --api-port=8080
            - --nexus-url=http://ha-nexus.demo-ha-pair.svc:9000
            - --ha-role=standby
            - --ha-peer=ha-bng-active.demo-ha-pair.svc:8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BNG_NODE_ID
              value: "bng-standby"
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bng-standby
  labels:
    app: bng
    role: standby
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
  selector:
    app: bng
    role: standby
